### ISSUE TITLE
desi/spectro/data/QL

### ISSUE THREAD

**Issue by weaverba137** [desihub/desiBackup#15]
I can't recall now whether `desi/spectro/data/QL` is archival.  If it is, it would not only need backup configuration, but a data model as well.

**Comment by sbailey** [comment]
QL sims and processed data should not be under `desi/spectro/data/`, which is reserved for real raw data (not sims, not processed data).  I've sent an email to @rstaten and @rkehoe requesting them to move it, or backup to tape and remove it.  In the meantime desiBackup could be configured to ignore this directory so that it doesn't count against the backup configuration status.
